# Blowfish theme for Hugo

name = "blowfish"
license = "MIT"
licenselink = "https://github.com/nunocoracao/blowfish/blob/main/LICENSE"
description = "tbd"

homepage = "https://github.com/nunocoracao/blowfish/"
demosite = "https://nunocoracao.github.io/blowfish/"

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["syntax higlighting", "dark mode", "emoji", "firebase", "views"]

[author]
  name = "Nuno Coracao"
  homepage = "https://nunocoracao.com/"

[original]
  author = "James Panther"
  homepage = "https://jamespanther.com/"
  repo = "https://github.com/jpanther/congo"
